services:
  mysql:
    image: mysql:9.6.0
    hostname: mysql-local
    container_name: mysql-local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql
