services:
  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ../data/redis:/data   # local folder on your machine
